project:
  type: website

website:
  title: "Moiz Deshmukh"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




