project:
  type: website

website:
  title: "Moiz Deshmukh"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      href: projects.qmd
      - projects.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



