project:
  type: website

website:
  title: "Moiz Deshmukh"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: resume.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true